#version: "3.8"
# Compose file build variables set in .env
services:
  app:
    platform: linux/amd64
    build: ./
    
    ## For Nvidia GPU's - You probably want to uncomment this
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]

    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"

    ports:
      - 7860:7860
    
    volumes:
      - ./docker-start.sh:/app/docker-start.sh
      - ./webui.sh:/app/webui.sh
      - ./stable-diffusion-webui:/app/stable-diffusion-webui
      - ./../collections/:/app/stable-diffusion-webui/models
      - ./../collections/embeddings:/app/stable-diffusion-webui/embeddings
      - ./../collections/outputs:/app/stable-diffusion-webui/outputs
      # - ./../collections/ControlNet:/app/stable-diffusion-webui/extensions/sd-webui-controlnet/models
    