#version: "3.8"
# Compose file build variables set in .env
services:
  app:
    platform: linux/amd64
    build: ./
    
    ## For Nvidia GPU's - You probably want to uncomment this
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]

    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"

    ports:
      - 8188:8188
    
    volumes:
      - ./docker-start.sh:/app/docker-start.sh
      - ./webui.sh:/app/webui.sh
      - ./ComfyUI:/app/ComfyUI

      - ./../collections/comfyui/custom_nodes:/app/ComfyUI/custom_nodes

      # - ./../collections/:/app/ComfyUI/models
      # - ./../collections/embeddings:/app/stable-diffusion-webui/embeddings
      - ./../collections/ControlNet:/app/ComfyUI/models/controlnet
      - ./../collections/clip:/app/ComfyUI/models/clip
      - ./../collections/clip_vision:/app/ComfyUI/models/clip_vision
      - ./../collections/diffusion_models:/app/ComfyUI/models/diffusion_models
      - ./../collections/embeddings:/app/ComfyUI/models/embeddings
      - ./../collections/gligen:/app/ComfyUI/models/gligen
      - ./../collections/hypernetworks:/app/ComfyUI/models/hypernetworks
      - ./../collections/Lora:/app/ComfyUI/models/loras
      - ./../collections/photomaker:/app/ComfyUI/models/photomaker
      - ./../collections/style_models:/app/ComfyUI/models/style_models
      - ./../collections/unet:/app/ComfyUI/models/unet
      - ./../collections/upscale_models:/app/ComfyUI/models/upscale_models
      - ./../collections/text_encoder:/app/ComfyUI/models/text_encoders
      - ./../collections/Stable-diffusion:/app/ComfyUI/models/checkpoints
      - ./../collections/VAE:/app/ComfyUI/models/vae
      - ./../collections/VAE-approx:/app/ComfyUI/models/vae_approx
      - ./../collections/RMBG-2.0:/app/ComfyUI/models/RMBG-2.0

      - ./../collections/outputs/comfyui/:/app/ComfyUI/output
      # - ./../collections/ControlNet:/app/stable-diffusion-webui/extensions/sd-webui-controlnet/models
    